version: '3'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: time_game
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  backend:
    build:
      context: .
      dockerfile: build/docker/Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - db
