"""empty message

Revision ID: 431cfdb4d56b
Revises: 6dbb8ed1f68f
Create Date: 2019-05-26 19:44:54.971043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '431cfdb4d56b'
down_revision = '6dbb8ed1f68f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('rfid_id', sa.Integer(), nullable=False),
    sa.Column('time', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('rfid_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('players')
    # ### end Alembic commands ###
