"""empty message

Revision ID: 5af998a069fe
Revises: b6731fbb61a2
Create Date: 2019-05-26 12:18:57.370125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5af998a069fe'
down_revision = 'b6731fbb61a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rfid_id', sa.Integer(), nullable=False),
    sa.Column('time', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'rfid_id')
    )
    op.drop_table('players')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('rfid_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('time', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='players_pkey')
    )
    op.drop_table('player')
    # ### end Alembic commands ###
