"""empty message

Revision ID: b2427cc7e8a2
Revises: 5af998a069fe
Create Date: 2019-05-26 12:19:20.000524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2427cc7e8a2'
down_revision = '5af998a069fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rfid_id', sa.Integer(), nullable=False),
    sa.Column('time', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'rfid_id')
    )
    op.drop_table('player')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rfid_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('time', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', 'rfid_id', name='player_pkey')
    )
    op.drop_table('players')
    # ### end Alembic commands ###
